Feat/search alarm by alarm
context-CODE/iplanner_api pull request #17
Opened 2023-01-12 16:49 UTC by ojosiels

Feita a função de pesquisar um alarm usando seu id

2023-01-12 19:09 UTC, thaygobajgar reviewed
src/services/alarms/getAlarmByAlarmId.service.ts
linha 14:
A verificação se o alarme existe vai ficar em um middleware, não precisa fazer a verificação no service

2023-01-12 21:19 UTC, samsks reviewed
Teste

2023-01-12 21:19 UTC, samsks commented on src/routes/alarm.routes.ts
> +
Removeu o import e rota de delete?

2023-01-12 21:21 UTC, samsks commented on src/controllers/alarms/index.ts
> +};
teste

2023-01-12 21:34 UTC, samsks requested changes
Precisa só mudar a nomenclatura da rota conforme enviei no slack

2023-01-12 21:58 UTC, samsks commented on src/controllers/alarms/getAlarmByAlarmId.controller.ts
> +  const data = await getAlarmByAlarmIdService(req.params.id);
listAlarmById

2023-01-12 22:11 UTC, ojosiels commented on src/controllers/alarms/getAlarmByAlarmId.controller.ts
> +  const data = await getAlarmByAlarmIdService(req.params.id);
Feito

2023-01-12 22:12 UTC, ojosiels reviewed
Mudado os nomes seguindo os padrões do projeto

2023-01-13 00:50 UTC, samsks approved these changes

2023-01-13 00:51 UTC, merged