fix/verificação da rota Finance
context-CODE/iplanner_api pull request #45
Opened 2023-01-16 17:58 UTC by nksn7

2023-01-16 18:43 UTC, samsks requested changes

2023-01-16 18:43 UTC, samsks commented on src/serializers/finance.serializer.ts
>  });
Consegue colocar no mesmo padrão da entidade? 
Precisamos de msgs para todos os campos e o typeError. Acertar o de value.
Se não for possível, me sinalize no slack que farei um commit antes pra alterar.

2023-01-16 18:43 UTC, samsks commented on src/serializers/finance.serializer.ts
>  });
Mesmo do finance serializer

2023-01-16 18:48 UTC, thaygobajgar reviewed
Nenhum ponto acrescentar além do Samuel

2023-01-17 22:57 UTC, samsks approved these changes

2023-01-17 22:57 UTC, merged